# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'editar_livro.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(808, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.voltar = QtWidgets.QPushButton(self.centralwidget)
        self.voltar.setGeometry(QtCore.QRect(410, 490, 141, 61))
        self.voltar.setObjectName("voltar")
        self.editar_salvar_livro = QtWidgets.QPushButton(self.centralwidget)
        self.editar_salvar_livro.setGeometry(QtCore.QRect(580, 490, 141, 61))
        self.editar_salvar_livro.setObjectName("editar_salvar_livro")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(100, 400, 581, 71))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_3 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_2.addWidget(self.label_3)
        self.editar_isbn = QtWidgets.QLineEdit(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.editar_isbn.setFont(font)
        self.editar_isbn.setObjectName("editar_isbn")
        self.horizontalLayout_2.addWidget(self.editar_isbn)
        self.label_5 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_2.addWidget(self.label_5)
        self.editar_editora = QtWidgets.QLineEdit(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.editar_editora.setFont(font)
        self.editar_editora.setObjectName("editar_editora")
        self.horizontalLayout_2.addWidget(self.editar_editora)
        self.layoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget_2.setGeometry(QtCore.QRect(100, 310, 581, 51))
        self.layoutWidget_2.setObjectName("layoutWidget_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget_2)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_2 = QtWidgets.QLabel(self.layoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.editar_title = QtWidgets.QLineEdit(self.layoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.editar_title.setFont(font)
        self.editar_title.setObjectName("editar_title")
        self.horizontalLayout.addWidget(self.editar_title)
        self.label_4 = QtWidgets.QLabel(self.layoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout.addWidget(self.label_4)
        self.editar_autor = QtWidgets.QLineEdit(self.layoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.editar_autor.setFont(font)
        self.editar_autor.setObjectName("editar_autor")
        self.horizontalLayout.addWidget(self.editar_autor)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(340, 40, 171, 41))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.layoutWidget_3 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget_3.setGeometry(QtCore.QRect(240, 170, 311, 41))
        self.layoutWidget_3.setObjectName("layoutWidget_3")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.layoutWidget_3)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_9 = QtWidgets.QLabel(self.layoutWidget_3)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_6.addWidget(self.label_9)
        self.buscaAutor_2 = QtWidgets.QLineEdit(self.layoutWidget_3)
        self.buscaAutor_2.setObjectName("buscaAutor_2")
        self.horizontalLayout_6.addWidget(self.buscaAutor_2)
        self.BottonBAutor_2 = QtWidgets.QPushButton(self.layoutWidget_3)
        self.BottonBAutor_2.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../../../Área de Trabalho/images.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.BottonBAutor_2.setIcon(icon)
        self.BottonBAutor_2.setObjectName("BottonBAutor_2")
        self.horizontalLayout_6.addWidget(self.BottonBAutor_2)
        self.layoutWidget_4 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget_4.setGeometry(QtCore.QRect(242, 219, 311, 61))
        self.layoutWidget_4.setObjectName("layoutWidget_4")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.layoutWidget_4)
        self.horizontalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_10 = QtWidgets.QLabel(self.layoutWidget_4)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_7.addWidget(self.label_10)
        self.BuscaISBN_2 = QtWidgets.QLineEdit(self.layoutWidget_4)
        self.BuscaISBN_2.setObjectName("BuscaISBN_2")
        self.horizontalLayout_7.addWidget(self.BuscaISBN_2)
        self.bottonBisbn_2 = QtWidgets.QPushButton(self.layoutWidget_4)
        self.bottonBisbn_2.setText("")
        self.bottonBisbn_2.setIcon(icon)
        self.bottonBisbn_2.setObjectName("bottonBisbn_2")
        self.horizontalLayout_7.addWidget(self.bottonBisbn_2)
        self.layoutWidget_5 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget_5.setGeometry(QtCore.QRect(240, 100, 311, 51))
        self.layoutWidget_5.setObjectName("layoutWidget_5")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.layoutWidget_5)
        self.horizontalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_11 = QtWidgets.QLabel(self.layoutWidget_5)
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_8.addWidget(self.label_11)
        self.buscTitle_2 = QtWidgets.QLineEdit(self.layoutWidget_5)
        self.buscTitle_2.setObjectName("buscTitle_2")
        self.horizontalLayout_8.addWidget(self.buscTitle_2)
        self.BottonBTitle_2 = QtWidgets.QPushButton(self.layoutWidget_5)
        self.BottonBTitle_2.setText("")
        self.BottonBTitle_2.setIcon(icon)
        self.BottonBTitle_2.setObjectName("BottonBTitle_2")
        self.horizontalLayout_8.addWidget(self.BottonBTitle_2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 808, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.voltar.setText(_translate("MainWindow", "Voltar"))
        self.editar_salvar_livro.setText(_translate("MainWindow", "Salvar"))
        self.label_3.setText(_translate("MainWindow", "ISBN:"))
        self.label_5.setText(_translate("MainWindow", "Editora:"))
        self.label_2.setText(_translate("MainWindow", "Titulo:"))
        self.label_4.setText(_translate("MainWindow", "Autor:"))
        self.label.setText(_translate("MainWindow", "EDITAR LIVRO"))
        self.label_9.setText(_translate("MainWindow", "Autor:"))
        self.label_10.setText(_translate("MainWindow", "ISBN:"))
        self.label_11.setText(_translate("MainWindow", "Título:"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
